blank_issues_enabled: false
contact_links:
  - name: Reckless RP Issue Tracker
    url: https://github.com/RecklessRP2/rlrp-issue-tracker/issues
    about: If your Issue/Suggestion relates to assets (Such as clothing, cars, etc), please raise it here.
  - name: Reckless RP Discord
    url: discord.gg/reckrp
    about: Join us on discord to discuss issues, ideas, etc.